services:
  transfer_db:
    image: postgres:14-alpine
    container_name: transfer_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transfer
    ports:
      - "5432:5432"
    volumes:
      - transfer_data:/var/lib/postgresql/data
    networks:
      - transfer_network

  transfer_api:
    build: .
    container_name: transfer_api
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules # Use anonymous volume for node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@transfer_db:5432/transfer
      - JWT_SECRET=9d0d50f8863ffae2c512429af8dba9f5
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_SECURE=false
      - EMAIL_USER=flvsantos300@gmail.com
      - EMAIL_PASSWORD="hthp+pvef+cxes+pqxm"
      - EMAIL_FROM="Transfer App <flvsantos300@gmail.com>"
    depends_on:
      - transfer_db
    networks:
      - transfer_network
    restart: unless-stopped
    # Enable hot-reloading
    command: sh -c "npm install && nodemon --legacy-watch --watch . --ext ts,json --exec ts-node src/server.ts"

networks:
  transfer_network:
    driver: bridge

volumes:
  transfer_data:
    driver: local
  node_modules: # Add named volume for node_modules
    driver: local

