services:
  transfer_db:
    image: postgres:14-alpine
    container_name: transfer_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - transfer_data:/var/lib/postgresql/data
    networks:
      - transfer_network

  transfer_api:
    build: .
    container_name: transfer_api
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/app
      - /usr/app/node_modules # Use anonymous volume for node_modules
    env_file:
      - .env
    depends_on:
      - transfer_db
    networks:
      - transfer_network
    restart: unless-stopped
    # Enable hot-reloading
    command: sh -c "npm install && nodemon --legacy-watch --watch . --ext ts,json --exec ts-node src/server.ts"

networks:
  transfer_network:
    driver: bridge

volumes:
  transfer_data:
    driver: local
  node_modules: # Add named volume for node_modules
    driver: local

healthcheck:
  test: ["CMD", "curl", "-f", "http://localhost"]
  interval: 30s
  timeout: 10s
  retries: 3

